services:
  db:
    restart: unless-stopped
    image: unmtransinfo/tictac_db:latest
    container_name: tictac-db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - tictac_db_data:/var/lib/postgresql
    # postgres settings based on: https://pgtune.leopard.in.ua/?dbVersion=18&osType=linux&dbType=web&cpuNum=8&totalMemory=16&totalMemoryUnit=GB&connectionNum=100&hdType=hdd
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=4GB
      -c effective_cache_size=12GB
      -c maintenance_work_mem=1GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=4
      -c effective_io_concurrency=2
      -c work_mem=38836kB
      -c huge_pages=off
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c checkpoint_timeout=15min
      -c max_worker_processes=8
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=8
      -c max_parallel_maintenance_workers=4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} && test -f /var/lib/postgresql/restore_complete"]
      interval: 60s
      timeout: 5s
      retries: 45
    deploy:
      resources:
        limits:
          cpus: 8
          memory: 16G

  api:
    restart: unless-stopped
    image: unmtransinfo/tictac_api:latest
    container_name: tictac-api
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      BEHIND_PROXY: "true"
    ports:
      - "127.0.0.1:${APP_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --workers 3 --port 8000
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/meta/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: 1 # recommended workers = (2 x $num_cores) + 1. 3 workers should be plenty for our use case (<50 concurrent users)
          memory: 2G
  ui:
    restart: unless-stopped
    image: unmtransinfo/tictac_ui:latest
    container_name: tictac-ui
    environment:
      - VITE_API_PROXY_TARGET=http://api:8000
    ports:
      - "127.0.0.1:${UI_PORT:-5173}:5173"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
volumes:
  tictac_db_data: