services:
  db:
    image: unmtransinfo/tictac_db:latest
    container_name: tictac-db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - tictac_db_data:/var/lib/postgresql
    command: >
      postgres
      -c max_wal_size=4GB
      -c checkpoint_timeout=15min
      -c checkpoint_completion_target=0.9
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} && test -f /var/lib/postgresql/restore_complete"]
      interval: 60s
      timeout: 5s
      retries: 45
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G

  api:
    image: unmtransinfo/tictac_api:latest
    container_name: tictac-api
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "127.0.0.1:${APP_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --workers 3 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/meta/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: 1 # recommended workers = (2 x $num_cores) + 1. 3 workers should be plenty for our use case (<50 concurrent users)
          memory: 2G

volumes:
  tictac_db_data:

