services:
  db:
    container_name: tictac-db
    image: unmtransinfo/tictac_db:latest
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - tictac_db_data:/var/lib/postgresql
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} && test -f /var/lib/postgresql/restore_complete" ]
      interval: 60s
      timeout: 5s
      retries: 20
    command: >
      postgres -c max_wal_size=4GB -c checkpoint_timeout=15min -c checkpoint_completion_target=0.9

  api:
    container_name: tictac-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    container_name: tictac-ui
    build:
      context: https://github.com/unmtransinfo/TICTAC-UI.git#main
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      - VITE_API_PROXY_TARGET=http://api:8000

volumes:
  tictac_db_data:
  static_files_tictac:

